### ISSUE TITLE
What if our attachment is not named "file"?

### ISSUE THREAD

**Issue by Sovietaced** [ImmaculatePine/hermitage#5]
I'm trying to use this but my attachment is called "image" so I'm getting an undefined method error. 
I looked over the docs but it doesn't look like this functionality is configureable?

**Comment by ImmaculatePine** [comment]
It is configurable.

Try this code in your `config/initializers/hermitage.rb`:

    Hermitage.configure :default do
      original -> item { item.image.url(:medium) }
      thumbnail -> item { image.url(:small) }
    end

**Comment by Sovietaced** [comment]
I tried that and had some errors for generating url_for or something. Anyways, I've moved on to something else.
